create table studentprofile (id int8 generated by default as identity, address varchar(255), first_name varchar(255), last_name varchar(255), phone_number varchar(255), studentreport_id int8, primary key (id));
create table studentreport (id int8 generated by default as identity, first_bimester float8, fourth_bimester float8, second_bimester float8, third_bimester float8, primary key (id));
alter table if exists studentprofile add constraint FK8abuyi1pnue8qbllc97yvr6o9 foreign key (studentreport_id) references studentreport;
